#!/bin/bash

if [ "$OS" == "Darwin" ]; then
    nuke=Nuke$NUKE_VERSION
else
    nuke=Nuke${NUKE_VERSION%v*}
fi

# run the script through Nuke
# nuke seems to eat the last arg
exec $nuke -t $0.py "$@" ""