// Generated by CoffeeScript 1.4.0
var mkpath;

mkpath = function(env) {
  var node;
  return ((function() {
    var _i, _len, _ref, _results;
    _ref = this.children;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      node = _ref[_i];
      if (node.mkpath != null) {
        _results.push(node.mkpath(env));
      }
    }
    return _results;
  }).call(this)).every(function(x) {
    return x != null;
  });
};
