// Generated by CoffeeScript 1.4.0
var buildArgv, generatePath, parentPath;

buildArgv = function() {
  var argv, flagPrefix, prop, _i, _len, _ref;
  argv = [this.script];
  _ref = this.params;
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    prop = _ref[_i];
    if (!prop.input && !prop.output && (this[prop.name] != null)) {
      if (this[prop.name] !== false && prop.noFlag !== true) {
        flagPrefix = prop.flagPrefix == null ? "--" : prop.flagPrefix;
        argv.push("" + flagPrefix + (prop.objectName.replace(/^__/, "")));
      }
      if (this[prop.name] !== true && this[prop.name] !== false) {
        argv.push(this[prop.objectName]);
      }
    }
  }
  return argv;
};

parentPath = function() {
  var branch, _ref;
  branch = this;
  while (((branch != null ? (_ref = branch.parent) != null ? _ref.className : void 0 : void 0) != null) !== "Branch") {
    branch = branch.parent;
  }
  if ((branch != null ? branch.elements.length : void 0) > 0) {
    return branch.elements[0].path;
  } else {
    return "";
  }
};

generatePath = function(name, index, frameSpec, ext) {
  if (frameSpec) {
    return "" + (parentPath()) + "tmp/" + name + "_" + index + "." + frameSpec + "." + ext;
  } else {
    return "" + (parentPath()) + "tmp/" + name + "_" + index + "." + ext;
  }
};
